# Generated by Django 5.2.1 on 2025-06-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nationalID',
            new_name='national_id',
        ),
    ]
