# Generated by Django 5.2.1 on 2025-06-26 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_profile_digital_signature_profile_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
