# Generated by Django 5.2.1 on 2025-07-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Fiscal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
