# Generated by Django 5.2.1 on 2025-07-28 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_role_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='El usuario que gestiona a este usuario (su superior en la jerarquía).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('COMPANY_ADMIN', 'Company Administrator'), ('COMPANY_MANAGER', 'Company Manager'), ('FINAL_USER', 'Final User')], default='FINAL_USER', max_length=50),
        ),
    ]
