# Generated by Django 5.2.1 on 2025-07-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_managed_by_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
    ]
