# Generated by Django 5.2.1 on 2025-07-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_role_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
