# Generated by Django 5.2.1 on 2025-07-29 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Role Code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Role Description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Role Active')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='The user who manages this user (their superior in the hierarchy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
