# Generated by Django 5.2.1 on 2025-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_role_alter_customuser_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID'),
        ),
    ]
