# Generated by Django 5.2.6 on 2025-11-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'Classification', 'verbose_name_plural': 'Classifications'},
        ),
        migrations.AddField(
            model_name='classification',
            name='color',
            field=models.CharField(blank=True, help_text='Hex Color or Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='users.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='classification',
            name='name',
            field=models.CharField(blank=True, help_text='Name (e.g., VIP, NORMAL)', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('company', 'name')},
        ),
        migrations.RemoveField(
            model_name='classification',
            name='code',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='description',
        ),
    ]
