# Generated by Django 5.2.1 on 2025-06-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Assets Categories',
            },
        ),
        migrations.CreateModel(
            name='ClaimAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tycker_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('exchange', models.TextField(blank=True, null=True)),
                ('lawsuit_type', models.TextField(blank=True, null=True)),
                ('eligibility', models.CharField(blank=True, max_length=255, null=True)),
                ('potencial_claim', models.CharField(blank=True, max_length=255, null=True)),
                ('total_settlement_fund', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('law_firm_handing_case', models.CharField(blank=True, max_length=255, null=True)),
                ('case_docket_number', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=255, null=True)),
                ('official_claim_filing_link', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Claim Action',
                'verbose_name_plural': 'Claim Actions',
            },
        ),
        migrations.CreateModel(
            name='ClaimActionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_for', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('activity', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Claim Action Transaction',
                'verbose_name_plural': 'Claim Action Transactions',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
                ('value_over_time', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets_photos/')),
                ('syntasis_summary', models.TextField(blank=True, null=True)),
                ('full_conversation_history', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('asset_date', models.DateField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_asset', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
