# Generated by Django 5.2.1 on 2025-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='trade_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
