# Generated by Django 5.2.1 on 2025-06-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_claimactiontransaction_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
