# Generated by Django 5.2.1 on 2025-07-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_claimactiontransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimactiontransaction',
            options={},
        ),
    ]
