# Generated by Django 5.2.1 on 2025-07-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_claimactiontransaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='value',
            new_name='acquisition_value',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='value_over_time',
            new_name='high_value',
        ),
        migrations.AddField(
            model_name='asset',
            name='estimated_value',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
