# Generated by Django 5.2.1 on 2025-07-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_claimactiontransaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='value_over_time',
            new_name='acquisition_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='value',
        ),
        migrations.AddField(
            model_name='asset',
            name='estimated_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='high_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
