# Generated by Django 5.2.6 on 2025-09-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_claimactiontransaction_options_importlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimAction',
        ),
        migrations.DeleteModel(
            name='ClaimActionTransaction',
        ),
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
