# Generated by Django 5.2.6 on 2025-09-19 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimActionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_for', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_date', models.CharField(blank=True, max_length=30, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('activity', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Claim Action Transaction',
                'verbose_name_plural': 'Claim Action Transactions',
            },
        ),
        migrations.CreateModel(
            name='ClaimAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tycker_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('exchange', models.TextField(blank=True, null=True)),
                ('lawsuit_type', models.TextField(blank=True, null=True)),
                ('eligibility', models.CharField(blank=True, max_length=255, null=True)),
                ('potencial_claim', models.CharField(blank=True, max_length=255, null=True)),
                ('total_settlement_fund', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('law_firm_handing_case', models.CharField(blank=True, max_length=255, null=True)),
                ('case_docket_number', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=255, null=True)),
                ('official_claim_filing_link', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim Action',
                'verbose_name_plural': 'Claim Actions',
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_job_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], max_length=10)),
                ('row_number', models.PositiveIntegerField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
            },
        ),
    ]
