# Generated by Django 5.2.6 on 2025-09-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_actions_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
