# Generated by Django 5.2.6 on 2025-12-16 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_alter_claimaction_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=30, null=True)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('cost_per_stock', models.FloatField()),
                ('amount', models.FloatField()),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actions Holdings',
                'verbose_name_plural': 'Actions Holdings',
            },
        ),
        migrations.CreateModel(
            name='ClassActionLawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tycker_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_stock', models.IntegerField(blank=True, null=True)),
                ('value_per_stock', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('claim_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('send_format', models.BooleanField(blank=True, default=False)),
                ('accept_claim', models.BooleanField(blank=True, default=False)),
                ('register_payment', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_actions_lawsuits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Action Lawsuit',
                'verbose_name_plural': 'Class Action Lawsuits',
            },
        ),
        migrations.CreateModel(
            name='TransactionStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_date', models.CharField(blank=True, max_length=30, null=True)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('cost_per_stock', models.FloatField()),
                ('amount', models.FloatField()),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('data_for', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Stock',
                'verbose_name_plural': 'Transaction Stocks',
                'constraints': [models.UniqueConstraint(fields=('user', 'symbol', 'trade_date'), name='unique_user_symbol_date')],
            },
        ),
    ]
