# Generated by Django 5.2.6 on 2025-12-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_actionsholdings_classactionlawsuit_transactionstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimactiontransaction',
            name='cost_per_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
