# Generated by Django 5.2.6 on 2025-12-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_claimactiontransaction_cost_per_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsholdings',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionsholdings',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='actionsholdings',
            name='cost_per_stock',
            field=models.DecimalField(decimal_places=4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='cost_per_stock',
            field=models.DecimalField(decimal_places=4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='claimactiontransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionstocks',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='transactionstocks',
            name='cost_per_stock',
            field=models.DecimalField(decimal_places=4, max_digits=24),
        ),
    ]
