# Generated by Django 5.2.6 on 2025-12-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_actionsholdings_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsholdings',
            name='end_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
