# Generated by Django 5.2.6 on 2025-12-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_actionsholdings_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionsholdings',
            old_name='finished',
            new_name='useless',
        ),
        migrations.AddField(
            model_name='actionsholdings',
            name='lot_number',
            field=models.IntegerField(default=0),
        ),
    ]
