# Generated by Django 5.2.6 on 2025-12-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_rename_finished_actionsholdings_useless_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsholdings',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_holdings', to='claim.claimactiontransaction'),
        ),
    ]
