# Generated by Django 5.2.6 on 2025-12-19 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0008_actionsholdings_transaction'),
        ('users', '0018_alter_customuser_options_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_actions_company', to='users.company'),
        ),
    ]
