# Generated by Django 5.2.6 on 2025-12-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_claimaction_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionStocks',
        ),
    ]
