# Generated by Django 5.2.6 on 2025-12-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_delete_transactionstocks'),
        ('users', '0018_alter_customuser_options_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimaction',
            name='claim_format_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimaction',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimaction',
            name='final_eligibility_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claimaction',
            name='method_send_claim_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimaction',
            name='start_eligibility_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_actions', to='users.company'),
        ),
    ]
