# Generated by Django 5.2.6 on 2025-12-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0011_claimaction_claim_format_name_claimaction_email_and_more'),
        ('users', '0018_alter_customuser_options_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactionlawsuit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_actions_lawsuits', to='users.company'),
        ),
    ]
