# Generated by Django 5.2.6 on 2025-12-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0012_classactionlawsuit_company'),
        ('users', '0018_alter_customuser_options_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsholdings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_holdings', to='users.company'),
        ),
        migrations.AlterField(
            model_name='actionsholdings',
            name='end_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='actionsholdings',
            name='start_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
