# Generated by Django 5.2.6 on 2025-12-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0013_actionsholdings_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimaction',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
