# Generated by Django 5.2.6 on 2025-12-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0014_claimaction_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classactionlawsuit',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classactionlawsuit',
            name='quantity_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classactionlawsuit',
            name='value_per_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
            preserve_default=False,
        ),
    ]
