# Generated by Django 5.2.6 on 2025-12-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0015_alter_classactionlawsuit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimaction',
            name='value_per_share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
            preserve_default=False,
        ),
    ]
