# Generated by Django 5.2.6 on 2025-12-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0016_claimaction_value_per_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactionlawsuit',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_actions_lawsuits', to='claim.actionsholdings'),
        ),
    ]
