# Generated by Django 5.2.6 on 2025-12-20 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0017_classactionlawsuit_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactionlawsuit',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_actions_lawsuits', to='claim.claimaction'),
        ),
    ]
