# Generated by Django 5.2.6 on 2025-12-22 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_classactionlawsuit_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactionlawsuit',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
