# Generated by Django 5.0.6 on 2025-05-20 15:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=30)),
                ('value_over_time', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='assets_photos/')),
                ('syntasis_summary', models.TextField(blank=True, null=True)),
                ('full_conversation_history', models.TextField(blank=True, null=True)),
                ('asset_date', models.DateField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_asset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Session ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Begin Session')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Uer')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AgentInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='texto de la pregunta')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='texto de la respuesta del agente')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('is_successful', models.BooleanField(default=False, verbose_name='interacción exitosa')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='mensaje de error (si hubo)')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='chat.chatsession', verbose_name='chat session')),
            ],
            options={
                'verbose_name': 'Registro de Interacción con Agente',
                'verbose_name_plural': 'Registros de Interacciones con Agente',
                'ordering': ['-timestamp'],
            },
        ),
    ]
