# Generated by Django 5.2.1 on 2025-06-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_session_id_alter_chatsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets_photos/'),
        ),
    ]
