# Generated by Django 5.2.1 on 2025-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_asset_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
