# Generated by Django 5.2.1 on 2025-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_assetcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
