# Generated by Django 5.2.1 on 2025-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_asset_attributes_alter_assetcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
