# Generated by Django 5.2.1 on 2025-06-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_assetcategory_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.assetcategory'),
        ),
    ]
