# Generated by Django 5.2.1 on 2025-06-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_asset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tycker_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('exchange', models.TextField(blank=True, null=True)),
                ('lawsuit_type', models.TextField(blank=True, null=True)),
                ('eligibility', models.CharField(blank=True, max_length=255, null=True)),
                ('potencial_claim', models.CharField(blank=True, max_length=255, null=True)),
                ('total_settlement_fund', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('law_firm_handing_case', models.CharField(blank=True, max_length=255, null=True)),
                ('case_docket_number', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=255, null=True)),
                ('official_claim_filing_link', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Claim Action',
                'verbose_name_plural': 'Claim Actions',
            },
        ),
    ]
