# Generated by Django 5.2.1 on 2025-06-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_claimaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ClaimAction',
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
