# Generated by Django 5.2.1 on 2025-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_asset_category_remove_asset_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinteractionlog',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinteractionlog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
