# Generated by Django 5.2.1 on 2025-07-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_agentinteractionlog_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinteractionlog',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
