# Generated by Django 5.2 on 2025-05-12 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='texto de la pregunta')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='texto de la respuesta del agente')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('is_successful', models.BooleanField(default=False, verbose_name='interacción exitosa')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='mensaje de error (si hubo)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_interactions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Registro de Interacción con Agente',
                'verbose_name_plural': 'Registros de Interacciones con Agente',
                'ordering': ['-timestamp'],
            },
        ),
    ]
