# Generated by Django 5.0.6 on 2025-05-24 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
