# Generated by Django 5.0.6 on 2025-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(upload_to='assets_photos/'),
        ),
    ]
